### ISSUE TITLE
Case of enums names

### ISSUE THREAD

**Issue by josesimoes** [STMicroelectronics/cmsis_device_l4#1]
**Describe the set-up**
- Using the latest version of this repo. 

**Additional context**
Enum values in stm32l4xx.h (line 180 and following) are using names all upper case. On a couple of projects I'm working with this is causing problems because some of them (namely ERROR and SET) are being replaced with defines coming from elsewhere. 
It's a generally accepted good practice to use ALL UPPER CASE names for defines and such, being the vars and similiar with camel case or equivalent names. 
I would suggest renaming those enums accordingly.

**Comment by ALABSTM** [comment]
Hi @josesimoes,

Would you mind giving an example of how could `ERROR` and `SET` enumerations be renamed?

Thanks,

**PS:** Best wishes for the new year 2022.

**Comment by josesimoes** [comment]
hey @ALABSTM !

Happy new 2022 for you too. 😄 

Because enums can be easilly mixed up with other vars, I would suggest including the type name in the enum for absolute disambiguation, like this:

```
typedef enum
{
  ErrorStatus_Success = 0,
  ErrorStatus_Error = !ErrorStatus_Success
} ErrorStatus;
```
and 

```
typedef enum
{
  FlagStatus_Reset = 0,
  FlagStatus_Set = !FlagStatus_Reset 
} FlagStatus, ITStatus;
```

If you find it too much, just rename the enums to remove the all upper case, like `Success`, `Error`, `Set`, etc.  
This way those wont be mistaken with compiler defines which are common practice to use all upper, like in `#define SET_BIT(...)` .

**Comment by ALABSTM** [comment]
See also [cmsis_device_l0#2](https://github.com/STMicroelectronics/cmsis_device_l0/issues/2)

**Comment by ALABSTM** [comment]
Hi @josesimoes,

Thank you for the clarification. The point has been submitted to our development teams. We will get back to you as soon as we get their feedback.

With regards,

**Comment by ALABSTM** [comment]
ST Internal Reference: 123347

**Comment by ALABSTM** [comment]
Hi @josesimoes,

I hope you are fine. Back to this point you tackled some time ago. We finally have the feedback of our development teams. While they may understand the reason behind such a request, they prefer to keep these definitions in uppercase as they are.

Please allow me to close this issue. Thank you for your comprehension.

With regards,
