### ISSUE TITLE
FLASH_SIZE_DATA_REGISTER still uses invalid (uint32_t) size designator

### ISSUE THREAD

**Issue by UweBonnes** [STMicroelectronics/cmsis_device_l4#3]
**Caution**
The Issues are strictly limited for the reporting of problem encountered with the software provided in this project.
For any other problem related to the STM32 product, the performance, the hardware characteristics and boards, the tools the environment in general, please post a topic in the [ST Community/STM32 MCUs forum](https://community.st.com/s/group/0F90X000000AXsASAW/stm32-mcus).

**Describe the set-up**
 * The board (either ST RPN reference or your custom board)
 * IDE or at least the compiler and its version

Use any preprocessor setup like
# if (FLASH_SIZE_DATA_REGISTER != 0x1FFF75E0
# pragma warning Probably no STM32L4 device
...
will raise an compiler error

**Describe the bug**

: error: missing binary operator before token "0x1FFF75E0"
 1147 | #define FLASH_SIZE_DATA_REGISTER ((uint32_t)0x1FFF75E0)
      |                                             ^~~~~~~~~~
/devel/en_apps/uart/nucleo_l476rg/../uart.c:65:7: note: in expansion of macro 'FLASH_SIZE_DATA_REGISTER'
   65 | # if (FLASH_SIZE_DATA_REGISTER != 0x1FFF75E0)
      |       ^~~~~~~~~~~~~~~~~~~~~~~~

**How To Reproduce**
1. Indicate the global behavior of your application project

2. The modules that you suspect to be the cause of the problem (Driver, BSP, MW ...)

3. The use case that generates the problem

4. How we can reproduce the problem

**Additional context**
If you have a first analysis or patch correction, thank you to share your proposal.

Use 
#define FLASH_SIZE_DATA_REGISTER 0x1FFF75E0UL

like for the rest of the header!

**Screenshots**

**Comment by TOUNSTM** [comment]
ST Internal Reference: 181112

**Comment by RJMSTM** [comment]
Fixed in : 1139cce704f53aba757021e4ea46830c61baf4ce
