### ISSUE TITLE
Missing USB register structure definitions.

### ISSUE THREAD

**Issue by PhucXDoan** [STMicroelectronics/cmsis_device_l4#4]
Is there a particular reason why there's [only one USB register structure](https://github.com/STMicroelectronics/cmsis_device_l4/blob/013bf0e41256ffbc2b539676f2007d08b297a86a/Include/stm32l476xx.h#L1448) defined in `stm32l476xx.h`? Definitions of other register structures like [`USB_OTG_DeviceTypeDef`](https://github.com/STMicroelectronics/cmsis_device_l4/blob/013bf0e41256ffbc2b539676f2007d08b297a86a/Include/stm32l476xx.h#L1038C1-L1060C25) are never used. I haven't really looked at other MCUs that also have the OTG core, but I suspect it's the same thing too.

If this is indeed a case of missing definitions, it should just be a simple patch of adding lines like `#define USB_OTG_DEVICE ((USB_OTG_DeviceTypeDef*) (USB_OTG_FS_PERIPH_BASE + USB_OTG_DEVICE_BASE))`.

**Comment by ALABSTM** [comment]
Hi @PhucXDoan,

Thank you for your report. However, there are no missing definitions and `USB_OTG_FS` is not a structure. It is rather an _alias_ of the right-hand-side expression as you can see below.

https://github.com/STMicroelectronics/cmsis_device_l4/blob/013bf0e41256ffbc2b539676f2007d08b297a86a/Include/stm32l476xx.h#L1448

`USB_OTG_FS_PERIPH_BASE` is the `USB OTG` registers base address, **i.e.**, the address of the first register in the memory, the addresses of the other registers being sequential to the first one's.

https://github.com/STMicroelectronics/cmsis_device_l4/blob/013bf0e41256ffbc2b539676f2007d08b297a86a/Include/stm32l476xx.h#L1292-L1293

The actual structured type is `USB_OTG_DeviceTypeDef`, each member of which represents one of the `USB OTG` registers as shown below. 

https://github.com/STMicroelectronics/cmsis_device_l4/blob/013bf0e41256ffbc2b539676f2007d08b297a86a/Include/stm32l476xx.h#L1035-L1060

To see examples of how this `USB_OTG_FS` alias is used, you have to browse the examples within the [STM32CubeL4](https://github.com/STMicroelectronics/STM32CubeL4) repository. [Here](https://github.com/STMicroelectronics/STM32CubeL4/blob/692ff21c2b84943aa8e8859e71600b8dc23aaf92/Projects/STM32L476G-EVAL/Applications/USB_Host/MSC_Standalone/Src/usbh_conf.c#L190) is one. I let you dig deeper into it to see how are the different registers accessed.

Please allow me to close this thread. Thank you for your comprehension.

With regards,
