### ISSUE TITLE
SMS[3] missing in STM32L4R5.svd

### ISSUE THREAD

**Issue by PerennialNovice** [STMicroelectronics/cmsis_device_l4#5]
I have been "forwarded" over here from [a discussion I opened on STM32Duino](https://github.com/orgs/stm32duino/discussions/2397#discussion-6811291):

While debugging I noticed that SMS[3] bit of the SMCR register for TIM2 is missing. I set that specific bit, and it appeared in the value for SMCR but in the bit fields only SMS[2:0] are covered.

![image](https://github.com/STMicroelectronics/cmsis_device_l4/assets/85557472/c9cae712-0cf7-4e21-8b7f-4c4ca0cf9347)

I manged to add it to the STM32L4R5.svd file, but only as a separate SMS3 bit.
It would be nicer to have the complete SMS[3:0] bitfield as one

As other timers are derived from TIM2, this does not only affect TIM2 but ost of the timers

I haven't checked other .svd files

**Comment by ALABSTM** [comment]
Hi @PerennialNovice,

Thank you for having reported. However, I am afraid I will redirect you to elsewhere once more. Indeed, as indicated in the **CONTRIBUTING.md** (paragraph 1, box 2) and the **README.md** ("Troubleshooting" section), this support channel is dedicated to issues found in the software items published within this repository.

Any other issue should be reported to the **ST Community**. I recommend the [STM32CubeIDE](https://community.st.com/t5/stm32cubeide-mcus/bd-p/stm32-mcu-cubeide-forum) forum.

Best of luck and thank you again for having reported. Please allow me to close this issue. Thank you for your comprehension.

With regards,
